'use client';
import {useLanguage} from '@/lib/i18n';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import type {Product,compareCampaign} from '@/lib/pricing';
const money=(v:number|null)=>v===null?'—':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(v);
const pct=(v:number)=>`${(100*v).toFixed(1)}%`;
export default function CampaignLab({product,cliff,version,busy,action}:{product:Product;cliff:number;version:number;busy:boolean;action:(name:string,extra?:any)=>Promise<any>}){
 const {t:tr}=useLanguage();
 const [price,setPrice]=useState(Math.min(product.inputs.mrp,Math.ceil(cliff*1.12))),[budget,setBudget]=useState(450),[response,setResponse]=useState<'effective'|'backfire'>('effective'),[result,setResult]=useState<ReturnType<typeof compareCampaign>|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setResult(null);const timer=setTimeout(async()=>{try{const q=new URLSearchParams({preview:'1',id:product.id,price:String(price),budget:String(budget),response});const r=await fetch(`/api/dashboard?${q}`,{signal:controller.signal});const d=await r.json() as any;if(!r.ok)throw Error(d.error);setResult(d);setError('');}catch(e){if(!controller.signal.aborted)setError((e as Error).message);}finally{if(!controller.signal.aborted)setLoading(false);}},250);return()=>{controller.abort();clearTimeout(timer)}},[product.id,version,price,budget,response]);
 return <section className="panel campaignLab"><p className="eyebrow">{tr("PRICE + ADVERTISING EXPERIMENT")}</p><h2>{tr("Can a higher price earn more?")}</h2><p>{tr("Advertising can buy exposure. Relevant creative can improve click-through, while a higher price can reduce clicks and conversion. Extra clicks are useful only if kept-sale profit covers the spend.")}</p>
 <div className="formGrid"><label className="field"><span>{tr("Test selling price (₹)")}</span><input type="number" min="1" step="1" value={price} onChange={e=>setPrice(Number(e.target.value))}/></label><label className="field"><span>{tr("Fixed weekly ad spend (₹)")}</span><input type="number" min="0" max="100000" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></label><label className="field"><span>{tr("Synthetic audience response")}</span><select value={response} onChange={e=>setResponse(e.target.value as any)}><option value="effective">{tr("Relevant audience: advertising can work")}</option><option value="backfire">{tr("Poor audience fit: advertising can backfire")}</option></select></label></div>
 {error&&<p className="error" role="alert">{tr(error)}</p>}{loading&&<p role="status">{tr("Calculating comparable scenarios…")}</p>}
 {result&&!loading&&<><div className="campaignTable"><table><thead><tr><th>{tr("Next-week projection")}</th><th>{tr("Benchmark-led, no ads")}</th><th>{tr("Higher price, no ads")}</th><th>{tr("Higher price + ads")}</th></tr></thead><tbody>{([
 ['Selling price',(r:any)=>money(r.price)],['Impressions',(r:any)=>r.impressions.toLocaleString('en-IN')],['Clicks',(r:any)=>r.clicks],['Click-through rate',(r:any)=>pct(r.ctr)],['Click-to-order rate',(r:any)=>pct(r.cvr)],['Orders',(r:any)=>r.orders],['Expected kept orders',(r:any)=>r.kept],['Ad spend',(r:any)=>money(r.adSpend)],['Contribution / day',(r:any)=>money(r.perDay)]
 ] as [string,(r:any)=>any][]).map(([label,f])=><tr key={label}><th>{tr(label)}</th>{[result.baseline,result.priceOnly,result.trial].map((r,i)=><td key={i}>{f(r)}</td>)}</tr>)}</tbody></table></div>
 <div className="note"><span><b>{result.trial.perDay>result.priceOnly.perDay?tr("Advertising adds value in this scenario"):tr("Advertising backfires versus the same price without ads")}:</b>{tr("advertising changes daily contribution by")}{" "}{money(result.trial.perDay-result.priceOnly.perDay)}{" "}{tr("at the same price. The combined price + ads change versus the benchmark-led baseline is")}{" "}{money(result.trial.perDay-result.baseline.perDay)}{" "}{tr("per day. These are simulated forecasts, not causal evidence. The no-ad baseline also respects the cost floor and ceiling.")}</span></div>
 {result.blocked&&<p className="fineprint">{tr("Preview only:")}{" "}{tr(result.blocked)}</p>}
 <Button disabled={busy||!!result.blocked||budget<=0} onClick={()=>action('startCampaign',{price,budget,response})}>{tr("Start 3-week price + ads test")}</Button></>}
 {product.campaign&&<div className="note"><span>{tr("Test running at")}{" "}{money(product.price)}{" "}{tr("with")}{" "}{money(product.campaign.budget)}{" "}{tr("per week. Price automation pauses during the test. It stops after 3 weeks or earlier if economic or quality limits fail.")}</span><Button variant="outline" disabled={busy} onClick={()=>action('endCampaign')}>{tr("Stop test")}</Button></div>}
 <details><summary>{tr("How this synthetic forecast works")}</summary><p>{tr("Organic impressions follow the lifecycle. Higher prices reduce click-through and click-to-order rates in both scenarios. The relevant-audience case uses ₹100 CPM and 6% starting paid CTR; poor fit uses ₹140 CPM and 3.5% paid CTR, with paid conversion at 28% of the organic rate. These are editable-code demo assumptions, not Meesho benchmarks.")}</p><p>{tr("Spend is fixed per week, even when there are no sales. Ad cost per dispatch = weekly spend ÷ forecast dispatches. The start gate checks a floor stressed by +5 percentage points RTO and +3 points returns. Wait two extra weeks after a test ends for all simulated returns to mature. A real test needs a matched holdout; this comparison is only a simulation.")}</p></details>
 </section>;
}
