"use client";
import {LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,ReferenceLine} from 'recharts';
import type {Product} from '@/lib/pricing';
import {growthSeries} from '@/lib/growth';
import {useLanguage} from '@/lib/i18n';
import {Help} from './language-controls';
export default function GrowthChart({product}:{product:Product}){
 const {t:tr}=useLanguage(),data=growthSeries(product);
 const scenario=product.inputs.scenario==='competitive'?'Competitor price pressure':product.inputs.scenario==='quality'?'Quality issue during growth':'Growth then softer demand';
 return <section className="panel chartPanel growthPanel"><div className="sectionHeader"><div><p className="eyebrow">{tr("ORDER GROWTH")}</p><h2 className="withInfo">{tr("Your growth vs competitor")}<Help title="How is order growth compared?"><p>{tr("Both lines show simulated weekly orders, before cancellations and returns. Your line uses recorded demo orders; the competitor is an illustrative benchmark, not a real seller or live Meesho data.")}</p><p>{tr("Index = weekly orders ÷ orders in the first common positive week × 100. An index of 150 means 50% more orders than that starting week. It is not market share or week-on-week growth.")}</p><p>{tr("The competitor follows the same growth-and-slowdown demand pattern. Under competitor pressure, its orders receive an assumed 35% boost from week 6, after the week-5 price cut. In the quality scenario, it has no seller-specific quality penalty.")}</p><p>{tr("Your orders reflect the demo price, demand, quality and advertising assumptions. The competitor does not use your advertising settings. These scenarios do not prove that price caused growth; compare returns and earnings before acting.")}</p><p>{tr("Advance weeks to add results. At least two weeks from a positive baseline are needed to show growth. Restarting clears this product’s growth history. This chart does not automatically change your price.")}</p></Help></h2></div><span className="tag">{tr("Simulated order index")}</span></div>
 <p className="growthCaption">{tr(scenario)} · {tr("Baseline = 100")}{data.baseWeek!==null?` · ${tr('Week')} ${data.baseWeek}`:''}</p>
 {data.baseWeek===null?<div className="growthEmpty">{tr("Advance the simulation until there is a week with orders to start the comparison.")}</div>:<><div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.rows} margin={{top:20,right:20,left:0,bottom:5}}><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#ebe4ed"/><XAxis dataKey="week" tickFormatter={w=>`W${w}`} tickLine={false} axisLine={false}/><YAxis width={54} domain={[0,'auto']} tickLine={false} axisLine={false}/><ReferenceLine y={100} stroke="#aa90a4" strokeDasharray="3 3"/><Tooltip labelFormatter={w=>`${tr('Week')} ${w}`} formatter={(v:any,n:any,item:any)=>[`${Number(v).toFixed(1)} · ${item.dataKey==='sellerIndex'?item.payload.sellerOrders:item.payload.peerOrders} ${tr('orders')}`,n]}/><Line isAnimationActive={false} name={tr("Your orders")} dataKey="sellerIndex" stroke="#620e50" strokeWidth={3} dot={{r:4}}/><Line isAnimationActive={false} name={tr("Simulated competitor orders")} dataKey="peerIndex" stroke="#d53c79" strokeWidth={2} strokeDasharray="6 3" dot={{r:3}}/></LineChart></ResponsiveContainer></div><div className="legend"><span><i style={{background:'#620e50'}}/>{tr("Your orders")}</span><span><i style={{background:'#d53c79'}}/>{tr("Simulated competitor orders")}</span></div>{data.rows.filter(r=>r.sellerIndex!==null).length<2&&<p className="growthCaption">{tr("One baseline week only; advance another week to compare growth.")}</p>}</>}
 </section>
}
