export type Inputs={name:string;category:string;mrp:number;cost:number;packaging:number;freight:number;fee:number;reverse:number;gst:number;lossRto:number;lossReturn:number;priorR:number;priorG:number;goal:number;sellerMin:number;sellerCap:number;step:number;adPlan:number;ads:boolean;capacity:number;stock:number;auto:boolean;scenario:string};
export type Cohort={impressions?:number;ctr?:number;cvr?:number;week:number;visits:number;orders:number;cancelled:number;dispatches:number;rto:number;returns:number;kept:number;rating:number;reviewCount:number;adSpend:number;price:number;actualCost:number};
export type Point={week:number;price:number|null;floor:number|null;required:number|null;cliff:number;stage:string;reason:string;contribution:number|null};
export type Campaign={budget:number;response:'effective'|'backfire';price:number;startedWeek:number};
export type Product={id:string;inputs:Inputs;week:number;price:number|null;cohorts:Cohort[];history:Point[];stock:number;campaign?:Campaign};
export const template:Inputs={name:'Printed cotton kurti',category:'Apparel',mrp:520,cost:215,packaging:9,freight:44,fee:0,reverse:105,gst:.05,lossRto:.08,lossReturn:.25,priorR:.15,priorG:.1,goal:12,sellerMin:0,sellerCap:100000,step:10,adPlan:8,ads:false,capacity:25,stock:2000,auto:true,scenario:'balanced'};
export function validate(input:any):Inputs{const x={...template,...input};if(typeof x.name!=='string'||!x.name.trim()||x.name.length>80)throw Error('Enter a product name (1–80 characters).');if(!['Apparel','Jewellery','Home'].includes(x.category)||!['balanced','quality','competitive'].includes(x.scenario))throw Error('Choose a supported category and scenario.');const limits:Record<string,[number,number]>={mrp:[1,100000],cost:[0,100000],packaging:[0,10000],freight:[0,10000],fee:[0,10000],reverse:[0,10000],gst:[0,.5],lossRto:[0,1],lossReturn:[0,1],priorR:[0,1],priorG:[0,1],goal:[0,100000],sellerMin:[0,100000],sellerCap:[1,100000],step:[1,10000],adPlan:[0,10000],capacity:[1,100000],stock:[0,1000000]};for(const[k,[lo,hi]]of Object.entries(limits))if(typeof x[k]!=='number'||!Number.isFinite(x[k])||x[k]<lo||x[k]>hi)throw Error(`Invalid ${k}: use ${lo}–${hi}.`);for(const k of ['ads','auto'])if(typeof x[k]!=='boolean')throw Error(`Invalid ${k}.`);return x;}
export function costs(i:Inputs,r:number,g:number,ad:number){const k=(1-r)*(1-g),terms={Packaging:i.packaging,'Forward freight':i.freight,Advertising:ad,'Platform fee':i.fee*(1-r),'Return handling':i.reverse*(1-r)*g,'Product cost & loss':i.cost*(k+r*i.lossRto+(1-r)*g*i.lossReturn)};const tc=Object.values(terms).reduce((a,b)=>a+b,0);return{k,terms,tc,floor:k>0?tc/k*(1+i.gst):null};}
export function signals(p:Product){const i=p.inputs,w=p.week,base=i.category==='Apparel'?355:i.category==='Jewellery'?249:449;const wave=[1,1,1,1.02,1.05,1.09,1.13,1.16,1.16,1.14,1.1,1.04,.98,.94,.91,.9,.9];const cliff=Math.round(base*wave[Math.min(w,16)]*(i.scenario==='competitive'&&w>=5?.82:1));const freight=i.freight+(w>=9?6:0),quality=i.scenario==='quality'&&w>=5;const resolved=p.cohorts.filter(c=>c.week<=w-1),mature=p.cohorts.filter(c=>c.week<=w-2);const nd=resolved.reduce((a,c)=>a+c.dispatches,0),nr=resolved.reduce((a,c)=>a+c.rto,0),delivered=mature.reduce((a,c)=>a+c.dispatches-c.rto,0),returns=mature.reduce((a,c)=>a+c.returns,0),kept=delivered-returns;const r=(50*i.priorR+nr)/(50+nd),g=(30*i.priorG+returns)/(30+delivered);const reviews=mature.reduce((a,c)=>a+c.reviewCount,0),rating=reviews?mature.reduce((a,c)=>a+c.rating*c.reviewCount,0)/reviews:null;const recent=mature.slice(-2),recentReviews=recent.reduce((a,c)=>a+c.reviewCount,0),recentRating=recentReviews?recent.reduce((a,c)=>a+c.rating*c.reviewCount,0)/recentReviews:null;const qualityFlag=recentReviews>=10&&recentRating!==null&&recentRating<3.5,evidence=nd>=50&&delivered>=30&&kept>=30;const counts=mature.map(c=>c.kept),decline=counts.length>=3&&counts.at(-1)!<counts.at(-2)!&&counts.at(-2)!<counts.at(-3)!;let stage=w===0?'Prepare':!evidence?(w<3?'Discover':'Validate'):qualityFlag?'Diagnose decline':decline&&w>=14?'Renew / recover':decline?'Diagnose decline':w>=9?'Maturity':w>=6?'Optimise':'Grow';return{cliff,freight,quality,r,g,nd,delivered,returns,kept,reviews,rating,recentRating,qualityFlag,evidence,stage,mature};}
export function calculate(p:Product){const s=signals(p),i={...p.inputs,freight:s.freight},activeAd=p.campaign?(p.campaign.budget/Math.max(1,traffic(p,p.price,p.campaign.budget,p.campaign.response).dispatches)):(i.ads?i.adPlan:0),c=costs(i,s.r,s.g,activeAd),h=Math.min(i.mrp,i.sellerCap),q=Math.min(s.cliff-1,h),required=c.floor===null?null:c.floor+i.goal*(1+i.gst),low=required===null?null:Math.ceil(Math.max(required,i.sellerMin)-1e-9),high=Math.floor(h);let recommendation:number|null=null,reason='',mode='Hold';if(low===null){reason='No kept sales expected. Fix delivery and return assumptions before listing.';mode='Blocked';}else if(low>high){reason='No whole-rupee price meets your contribution goal within the ceiling. Review the goal, cost or offer.';mode='Blocked';}else{const target=Math.floor(q),normal=target>=low;let desired=normal?target:low;mode=normal?'Competitive':'Cost-based test';reason=normal?'Competitor minus ₹1 covers your floor and contribution goal.':'Competitor minus ₹1 does not cover your goal. Test the required price above the benchmark.';if(p.price!==null){if(p.price<low||p.price>high){desired=Math.max(low,Math.min(high,desired));reason='Protective correction: the previous price is outside the economic or MRP limits.';mode='Protective correction';}else if(s.qualityFlag||!s.evidence||s.stage==='Renew / recover'){desired=p.price;mode='Hold';reason=s.qualityFlag?'Quality signal: hold the valid price and fix the listing before discounting.':!s.evidence?'Hold while dispatch and return outcomes mature. Sparse data is not a reason to discount.':'Pause replenishment or consider another channel. Clearance needs separate economics.';}else{desired=Math.max(low,Math.min(high,Math.max(p.price-i.step,Math.min(p.price+i.step,desired))));if(desired===p.price){mode='Hold';reason='The current price remains appropriate. Keep price and ad tests separate.';}}}if(p.campaign&&p.price!==null&&p.price>=low&&p.price<=high){desired=p.price;mode="Advertising test";reason="Hold the agreed test price above the benchmark. Judge settled contribution, not clicks alone.";}recommendation=desired;}
 const tc0=costs(i,s.r,s.g,0).tc,stress=costs(i,Math.min(.99,s.r+.05),Math.min(.99,s.g+.03),0);const headroom=p.price===null||!c.k?null:Math.min(c.k*(p.price/(1+i.gst)-i.goal)-tc0,stress.k*(p.price/(1+i.gst)-i.goal)-stress.tc);const contribution=p.price===null||!c.k?null:p.price/(1+i.gst)-c.tc/c.k;const last=s.mature.at(-1),matureContribution=last?last.kept*last.price/(1+i.gst)-last.actualCost:null;return{...s,...c,required,low,high,q,h,recommendation,reason,mode,headroom,contribution,matureContribution,perDay:matureContribution===null?null:matureContribution/7,activeAd,tc0};}
export function record(p:Product,reason:string){const c=calculate(p);p.history.push({week:p.week,price:p.price,floor:c.floor,required:c.required,cliff:c.cliff,stage:c.stage,reason,contribution:c.contribution});}
export function addProduct(inputs:Inputs,id=crypto.randomUUID()):Product{const p:Product={id,inputs,week:0,price:null,cohorts:[],history:[],stock:inputs.stock};const c=calculate(p);p.price=c.recommendation;record(p,'Initial listing: '+c.reason);return p;}
// All effects below are explicit synthetic assumptions, not estimated Meesho effects.
export function traffic(p:Product,price:number|null,budget=0,response:'effective'|'backfire'='effective'){
 const s=signals(p),i=p.inputs,w=p.week+1,phase=w<3?.45:w<7?1:w<11?1.25:w<14?.72:.35;
 const baseVisits=Math.round((450+w*48)*phase),gap=price===null?0:(price-s.cliff)/Math.max(s.cliff,1);
 const priceClickFactor=Math.max(.2,Math.min(1.4,1-gap*.4));
 const organicImpressions=Math.round(baseVisits/.05),paidImpressions=price===null?0:Math.round(budget/(response==='effective'?100:140)*1000);
 const organicClicks=price===null?0:Math.round(organicImpressions*.05*priceClickFactor),paidClicks=Math.round(paidImpressions*(response==='effective'?.06:.035)*priceClickFactor);
 const conversion=price===null?0:.095*Math.max(.12,Math.min(1.4,1-gap*2))*(s.quality?.55:1);
 const orders=Math.round(organicClicks*conversion+paidClicks*conversion*(response==='effective'?.95:.28));
 const cancelled=Math.round(orders*.06),dispatches=Math.floor(Math.max(0,Math.min(orders-cancelled,i.capacity*7,p.stock)));
 const rto=Math.round(dispatches*Math.min(1,i.priorR+(w>=11?.04:0)+(w%3-1)*.01)),returns=Math.round((dispatches-rto)*Math.min(1,i.priorG+(s.quality?.17:0))),kept=dispatches-rto-returns;
 const adSpend=budget,actualCost=dispatches*(i.packaging+s.freight)+adSpend+(dispatches-rto)*i.fee+returns*i.reverse+i.cost*(kept+rto*i.lossRto+returns*i.lossReturn);
 const clicks=organicClicks+paidClicks,impressions=organicImpressions+paidImpressions,contribution=kept*(price??0)/(1+i.gst)-actualCost;
 return{price,impressions,organicImpressions,paidImpressions,clicks,paidClicks,ctr:impressions?clicks/impressions:0,cvr:clicks?orders/clicks:0,orders,cancelled,dispatches,rto,returns,kept,adSpend,actualCost,contribution,perDay:contribution/7};
}
export function compareCampaign(p:Product,price:number,budget:number,response:'effective'|'backfire'){
 if(!Number.isFinite(price)||!Number.isInteger(price)||price<1||price>100000||!Number.isFinite(budget)||budget<0||budget>100000||!['effective','backfire'].includes(response))throw Error('Use a whole-rupee price, budget of 0–100,000 and a supported response.');
 const s=signals(p),i={...p.inputs,freight:s.freight},ceiling=Math.floor(Math.min(i.mrp,i.sellerCap));
 const noAdFloor=costs(i,s.r,s.g,0).floor,basePrice=noAdFloor===null?null:Math.max(Math.ceil(Math.max(noAdFloor+i.goal*(1+i.gst),i.sellerMin)),Math.min(ceiling,s.cliff-1));
 const baseline=traffic(p,basePrice!==null&&basePrice<=ceiling?basePrice:null,0),priceOnly=traffic(p,price,0),trial=traffic(p,price,budget,response);
 const perDispatch=trial.dispatches?budget/trial.dispatches:Infinity;
 const stressed=costs(i,Math.min(.99,s.r+.05),Math.min(.99,s.g+.03),Number.isFinite(perDispatch)?perDispatch:0);
 const required=stressed.floor===null?null:Math.ceil(Math.max(stressed.floor+i.goal*(1+i.gst),i.sellerMin));
 let blocked= p.week>=16?'Restart the lifecycle before testing.':p.campaign?'Finish the active test first.':!baseline.dispatches?'No viable baseline or available stock/capacity.':!trial.dispatches?'No dispatches expected; advertising would still cost money.':price>ceiling?'Test price exceeds the MRP / seller ceiling.':required===null||price<required?'This test misses the stressed cost floor or contribution goal. Raise price, reduce spend or change the offer.':null;
 return{baseline,priceOnly,trial,required,ceiling,blocked,response,budget,price};
}
export function startCampaign(p:Product,price:number,budget:number,response:'effective'|'backfire'){
 const test=compareCampaign(p,price,budget,response);if(test.blocked)throw Error(test.blocked);
 if(budget<=0)throw Error('Set a positive weekly advertising budget.');
 p.campaign={price,budget,response,startedWeek:p.week};p.price=price;p.inputs.ads=true;p.inputs.auto=false;
 record(p,'Started a bounded 3-week synthetic price + advertising test. Fixed spend is charged even if clicks do not convert.');
}
export function endCampaign(p:Product,reason='Advertising test stopped.'){
 delete p.campaign;p.inputs.ads=false;p.inputs.auto=true;p.price=calculate(p).recommendation;record(p,reason+' Returned to normal price recommendations.');
}
export function restart(p:Product){
 // Seller assumptions remain; stock, simulation outcomes and history restart for this product only.
 const fresh=addProduct({...p.inputs,ads:false,auto:true},p.id);delete p.campaign;Object.assign(p,fresh);record(p,'Lifecycle restarted at week 0 with current seller assumptions and starting stock.');return p;
}
export function advance(p:Product){
 if(p.week>=16)throw Error('This demo ends at week 16. Use Restart lifecycle to begin again.');
 const c=calculate(p),i=p.inputs,w=p.week+1;
 const preliminary=traffic(p,p.price,0),budget=p.campaign?.budget??(i.ads?preliminary.dispatches*i.adPlan:0);
 const t=traffic(p,p.price,budget,p.campaign?.response??'effective');
 const rating=c.quality?3.1:Math.min(4.5,4.05+w*.025);
 p.cohorts.push({...t,week:w,visits:t.clicks,price:p.price??0,rating,reviewCount:Math.round(t.kept*.32)});
 p.stock=Math.max(0,p.stock-t.dispatches);p.week=w;
 if(p.campaign){const updated=calculate(p);if(w-p.campaign.startedWeek>=3||updated.qualityFlag||p.price===null||updated.low===null||p.price<updated.low||p.price>updated.high){endCampaign(p,'Bounded test finished or economic/quality guardrail triggered. Wait two more demo weeks for the final return cohort.');return p;}record(p,'Advertising test in progress. More clicks may still mean fewer kept sales or lower profit.');return p;}
 let next=calculate(p),reason=next.reason;if(i.ads&&(next.headroom===null||next.headroom<i.adPlan||next.qualityFlag)){i.ads=false;reason='Paused ads: headroom or quality check failed. '+reason;next=calculate(p);}if(i.auto)p.price=next.recommendation;record(p,i.auto?reason:'Automatic pricing off; recommendation only. '+reason);return p;
}
export function seeds(){return[addProduct({...template},'kurti-demo'),addProduct({...template,name:'Brass stud combo',category:'Jewellery',mrp:399,cost:105,freight:38,reverse:80,gst:.03,scenario:'competitive'},'stud-demo'),addProduct({...template,name:'Cotton cushion cover',category:'Home',mrp:699,cost:235,freight:56,reverse:110,gst:.05,scenario:'quality'},'cushion-demo')];}
